# Bernoulli test: randint( )  vs  choice( )

In [119]:
# in 'randint()': the arguemt is a 'limit' 
# in 'choice()': the argument is not a 'limit'....so there is no inclusive/exclusive, but we can set 'biased test' 
# by offering specific probability values!

# we should **specify**..what the success(0) or failure(1) or Head(0) or Tail(1) or dice numbers(1,2,3,4,5,6 = np.arange(1,7))

In [1]:
import numpy as np
import matplotlib.pyplot as plt
% matplotlib inline

In [2]:
# 5 by 5 array of "Standard Normal" sample
np.random.randn(5,5)

array([[ 1.14230331,  0.03516998,  0.45415637,  2.84439575,  0.650921  ],
       [-0.61768282, -1.54742874,  0.72010905, -0.17261075, -0.25563092],
       [-1.73028433, -0.60160122,  1.43982635,  0.1832981 , -0.52189503],
       [-0.20852813,  0.52709929,  0.16179152,  1.10397799,  0.703066  ],
       [-1.74659098,  1.2557002 , -0.28655409, -0.51056736, -0.63933845]])

In [16]:
# Basic sorting of 1D arrays is easy
arr_1= np.random.randn(8)
arr_1
#arr_1.sort()

array([ 1.20208385, -2.41360083,  2.29299119,  2.34975944,  0.13781292,
        0.5710256 ,  0.05026874,  0.64276098])

In [15]:
# 2D arrays require an axis - this sorts by row
arr_2 = np.random.randn(8,3); arr_2
#arr_2.sort(1) #by row
#arr_2.sort(0) #by col

array([[ 1.11123341, -0.7018184 , -1.05693589],
       [ 0.29325758, -0.41673121, -0.42419421],
       [-1.22727483,  1.60655974,  0.01153593],
       [-0.54635033,  0.29398722, -0.49978744],
       [-0.08692454, -1.53666109, -0.12212281],
       [-0.18148977, -1.11247379,  0.0197066 ],
       [-1.16551722, -1.07315204,  0.69995806],
       [ 0.20662637,  2.13586457, -0.37249315]])

In [26]:
# Bernoulli..outcome of one coin flip:
# Setting an outcome limit: lower bound '0'...inclusive and it's a default, upper bound '1'...exclusive so..2 
# so outcome is NO.of success !
# size = 1 as a default so..
np.random.randint(0, 2)

0

In [30]:
# outcomes of ten thousand coin flips
np.random.randint(0, 2, size=10000)

array([0, 1, 1, ..., 0, 0, 1])

In [54]:
# 2D array
np.random.randint(0, 2, size=[10000,4])

array([[1, 0, 1, 0],
       [0, 1, 1, 1],
       [1, 0, 0, 1],
       ..., 
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0]])

In [37]:
# mean outcome array of ten thousand coin flips-unbiased coin
np.random.randint(0, 2, size=10000).mean()

0.51259999999999994

In [43]:
# outcome of one coin flip 
# = np.random.randint(0, 2) 
np.random.choice([0, 1])

1

In [44]:
# outcome of ten thousand coin flips
np.random.choice([0, 1], size=10000)

array([0, 1, 1, ..., 1, 1, 0])

In [45]:
# mean outcome of ten thousand coin flips-unbiased coin
np.random.choice([0, 1], size=10000).mean()

0.50239999999999996

In [46]:
# outcomes of ten thousand "biased" coin flips
np.random.choice([0, 1], size=10000, p=[0.8, 0.2])

array([0, 1, 0, ..., 1, 1, 0])

In [47]:
# mean outcome of ten thousand "biased" coin flips
np.random.choice([0, 1], size=10000, p=[0.8, 0.2]).mean()

0.20269999999999999

### 1. Two fair coin flips produce exactly two heads

In [48]:
# simulate 1 million tests of two fair coin flips...two? then size=[x,2]..it's a begining of 2D array! 
tests = np.random.randint(0, 2, size=(int(1e6), 2))

# sums of all tests
test_sums = tests.sum(axis=1)

# proportion of tests that produced exactly two heads ???????????? [0, 0]
(test_sums == 0).mean()

0.24962500000000001

In [49]:
tests 

array([[1, 1],
       [1, 1],
       [1, 1],
       ..., 
       [0, 1],
       [0, 1],
       [1, 1]])

In [50]:
test_sums

array([2, 2, 2, ..., 1, 1, 2])

### 2. Three fair coin flips produce exactly one head

In [106]:
# simulate 1 million tests of three fair coin flips
tests = np.random.randint(0,2, size=[int(1e6), 3])

# sums of all tests
test_sums = tests.sum(axis=1)

# proportion of tests that produced exactly one head ???????????? [0,1,1],[1,0,1],[1,1,0]
(test_sums == 2).mean()

0.37486399999999998

### 3. Three biased coin flips with P(H) = 0.6 produce exactly one head

In [107]:
# simulate 1 million tests of three bias coin flips
tests = np.random.choice([0,1], size=[1000000, 3], p=[0.6, 0.4])

# sums of all tests
test_sums = tests.sum(axis=1)

# proportion of tests that produced exactly one head ????????????? [0,1,1],[1,0,1],[1,1,0]
(test_sums==2).mean()

0.28793999999999997

### 4. A die rolls an even number

In [115]:
# simulate 1 million tests of one die roll
#tests = np.random.randint(1, 7, size=int(1e6)); tests
tests = np.random.choice(np.arange(1, 7), size=int(1e6))


# proportion of tests that produced an even number ???????????????? 
(tests % 2 == 0).mean()

0.49996000000000002

### 5. Two dice roll a double

In [118]:
# simulate the first million die rolls
first = np.random.randint(1, 7, size=int(1e6))

# simulate the second million die rolls
second = np.random.randint(1, 7, size=int(1e6))

# proportion of tests where the 1st and 2nd die rolled the same number ??????????????
(first == second).mean()

0.16719800000000001

In [1]:
import numpy as np


In [3]:
1/np.exp(0.7418)

0.4762558829340936

In [4]:
1/np.exp(0.0008)

0.99920031991468372

In [5]:
1/np.exp(-1.6271)

5.0890949229147928